spring:
  h2:
    console:
      enabled: true
  batch: 
    jdbc:
      initialize-schema: "always"
    job:
      enabled: false
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        formatSql: true